### PR TITLE
Added sklearn-requirements to be <1.2 & > 1.1

### PR DESCRIPTION
**Pull request by prasys**
Kia ora & salam sejahtera!

Based on #141 issued raised by @farisshamsur . I've added a requirements check so that if someone runs malaya, we still have support for sklearn and not get those pesky deprecated warnings or other changes that are being done to sklearn.

Ideally, I'll be working to make it sklearn > 1.2 friendly by changing some of the functions. Until then, it would be a stop-gap measure

Amazing job that you have done for the community

Thanks

### CODE REVIEW

**Comment by huseinzol05** [comment]
is it break kalau guna > 1.2?

**Comment by MagusWyvern** [comment]
I tried installing using the above changes in the `requirements.txt` file and everything seems to work fine.

Tested on Ubuntu-22.04 with Tensorflow 2.15.0, below is me testing the `malaya` library in an interactive Python terminal:

``` 
(pr) root@localhost:~# python3                          
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux                                              
Type "help", "copyright", "credits" or "license" for more information.                                          
>>> import malaya                                       
Cannot import beam_search_ops from Tensorflow Addons, ['malaya.jawi_rumi.deep_model', 'malaya.phoneme.deep_model', 'malaya.rumi_jawi.deep_model', 'malaya.stem.deep_model'] will not available to use, make sure Tensorflow Addons version >= 0.12.0                                    check compatible Tensorflow version with Tensorflow Addons at https://github.com/tensorflow/addons/releases     bs4 is not installed, `malaya.text.function.remove_html_tags` will use regex                                    
>>> model = malaya.sentiment.transformer(model = 'tiny-albert')                                                 
model.pb: 100%|████| 23.5M/23.5M [00:03<00:00, 7.70MB/s]
sp10m.cased.v10.vocab: 100%|█| 569k/569k [00:00<00:00, 5
sp10m.cased.v10.model: 100%|█| 779k/779k [00:01<00:00, 6
>>> model.predict_words('Dia ni dlm pemerhatian kita,,,bole dkatakn "gertak kuat",,,bhsa utra kta "gempaq kuat",', bins_size = 0.01)                                    
2024-01-29 09:10:40.083302: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:388] MLIR V1 optimization pass is not enabled
```

**Comment by MagusWyvern** [comment]
> is it break kalau guna > 1.2?

After testing it does indeed break:

```
Traceback (most recent call last):                        
    File "/root/test.py", line 40, in <module>                
        r = model.sentence_level(isu_kerajaan)                
    File "/root/pr2/lib/python3.10/site-packages/herpetologist/__init__.py", line 100, in check            
        return func(*args, **kwargs)                          
    File "/root/pr2/lib/python3.10/site-packages/malaya/model/extractive_summarization.py", line 212, in sentence_level 
original_strings, ranked_sentences, top_words, cluster_top_words = self._vectorize_sentence(                  
    File "/root/pr2/lib/python3.10/site-packages/malaya/model/extractive_summarization.py", line 112, in _vectorize_sentence                                                  
        features = self.vectorizer.get_feature_names()      
AttributeError: 'SkipGramCountVectorizer' object has no attribute 'get_feature_names'. Did you mean: 'get_feature_names_out'?
```

This is a good PR to temporarily solve the issue, I'll revert it is there's any breaking changes but I tested it earlier (see my previous comment) and all seems a-okay.

**Comment by huseinzol05** [comment]
need to support at least stable version sklearn

**Comment by prasys** [comment]
Memang break

I am rewriting some of the functions balik to support sklearn 1.2 (but holidaying in malaysia)

hopefully to submit a PR in a couple of weeks time :)

**Comment by huseinzol05** [comment]
its ok, im doing it, we are going to release 5.1 asap

**Comment by huseinzol05** [comment]
Latest master support >=1.2, https://github.com/mesolitica/malaya/blob/master/requirements.txt#L2

**Pull request closed without merging**
